/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.NewsFeedUser;
import hr.algebra.utilities.ImageTransferHandler;
import hr.algebra.view.AddUserDialog;
import hr.algebra.view.EditArticlesPanel;
import hr.algebra.view.AdminPanel;
import hr.algebra.view.ImageDropFrame;
import hr.algebra.view.LoginDialog;
import hr.algebra.view.UploadArticlesPanel;
import javax.swing.TransferHandler;

/**
 *
 * @author daniel.bele
 */
public class ArticleManager extends javax.swing.JFrame {

    private static final String UPLOAD_ARTICLES = "Upload articles";
    private static final String EDIT_ARTICLES = "Edit articles";
    private static final String ADMIN_PANEL = "Admin articles";
    
    private Repository repository;
    private NewsFeedUser loggedInUser; 
    private final TransferHandler imageHandler = new ImageTransferHandler();
    private ImageDropFrame imageDropFrame = new ImageDropFrame(imageHandler);

    
    public ArticleManager(NewsFeedUser user) {
	this.loggedInUser = user;
        repository = RepositoryFactory.getRepository();
        initComponents();
        try {
            configurePanels();
        } catch (Exception exception) {
            System.out.println(exception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        tpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        miBigImage = new javax.swing.JMenuItem();
        jAddUser = new javax.swing.JMenu();
        jNewUser = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        miBigImage.setText("Big Image");
        miBigImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBigImageActionPerformed(evt);
            }
        });
        jMenu1.add(miBigImage);

        jMenuBar1.add(jMenu1);

        jAddUser.setText("Add User");

        jNewUser.setSelected(true);
        jNewUser.setText("new user");
        jNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewUserActionPerformed(evt);
            }
        });
        jAddUser.add(jNewUser);

        jMenuBar1.add(jAddUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void jNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewUserActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
            AddUserDialog addUserDialog = new AddUserDialog(null, true);
            addUserDialog.setVisible(true);
        });
    }//GEN-LAST:event_jNewUserActionPerformed

    private void miBigImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBigImageActionPerformed

        imageDropFrame.setVisible(true);
    }//GEN-LAST:event_miBigImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticleManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(() -> {
            // Show login dialog first
            LoginDialog loginDialog = new LoginDialog(null, true);
            loginDialog.setVisible(true);
            
            

            NewsFeedUser user = loginDialog.getLoggedInUser();
            if (user != null) {
                ArticleManager app = new ArticleManager(user);
                app.setVisible(true);
            } else {
                System.exit(0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAddUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JCheckBoxMenuItem jNewUser;
    private javax.swing.JMenuItem miBigImage;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    

    private void configurePanels() throws Exception {
        tpContent.removeAll(); 
        tpContent.add(EDIT_ARTICLES, new EditArticlesPanel());
        tpContent.add(UPLOAD_ARTICLES, new UploadArticlesPanel());
        System.out.println("User is admin: " + loggedInUser.getIsAdmin());
        if (loggedInUser.getIsAdmin()) {
            tpContent.add(ADMIN_PANEL, new AdminPanel());
        }else{
            jMenuBar1.remove(jAddUser);
        }
    }


    


}
