/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.utilities.MessageUtils;
import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;
import static javax.swing.text.html.HTML.Attribute.DIR;

/**
 *
 * @author paola
 */
public class AdminPanel extends javax.swing.JPanel {

    
    Repository repository = RepositoryFactory.getRepository();
    ImageIcon loadingIcon = new ImageIcon(getClass().getResource("/assets/spinner.gif"));
    private static final String DIR = "assets";

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteArticles = new javax.swing.JButton();
        jLblLoadingImg = new javax.swing.JLabel();

        btnDeleteArticles.setText("Delete Articles");
        btnDeleteArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteArticlesActionPerformed(evt);
            }
        });

        jLblLoadingImg.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLblLoadingImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblLoadingImg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteArticlesActionPerformed
        // TODO add your handling code here:
    
   
        
        
        jLblLoadingImg.setIcon(loadingIcon);
        jLblLoadingImg.setVisible(true);

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                repository.deleteArticles();
                clearAssetsFolder();
                return null;
            }

            @Override
            protected void done() {
                // This runs on the UI thread after doInBackground() is finished
                try {
                    get(); 
                    javax.swing.JOptionPane.showMessageDialog(
                        AdminPanel.this, 
                        "All articles have been deleted.", 
                        "Success", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE
                    );
                } catch (Exception ex) {
                    System.out.println("Error deleting articles: " + ex);
                    javax.swing.JOptionPane.showMessageDialog(
                        AdminPanel.this, 
                        "An error occurred while deleting articles.", 
                        "Error", 
                        javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                } finally {
                    jLblLoadingImg.setVisible(false);
                    jLblLoadingImg.setIcon(null); 
                }
            }
        };

        worker.execute();
    }//GEN-LAST:event_btnDeleteArticlesActionPerformed

    private void clearAssetsFolder() {

        Path dirPath = Paths.get(DIR);

        if (Files.exists(dirPath) && Files.isDirectory(dirPath)) {
            try (DirectoryStream<Path> stream = Files.newDirectoryStream(dirPath)) {
                for (Path file : stream) {
                    if (Files.isRegularFile(file)) {
                        Files.delete(file);
                    }
                }
                
            } catch (IOException ex) {
                Logger.getLogger(EditArticlesPanel.class.getName()).log(Level.SEVERE, "Error clearing assets folder", ex);
                MessageUtils.showErrorMessage("Error", "Could not clear all assets. A file might be in use.");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteArticles;
    private javax.swing.JLabel jLblLoadingImg;
    // End of variables declaration//GEN-END:variables
}
